version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: usersDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./postg:/data
     # - ./iternal/postg/migrate/1_init.up.sql:/docker-entrypoint-initdb.d/1_init.up.sql
  gRPC:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    image: culc-grpc:latest
